/**
 * Static catalog of sports / leagues / teams the mock provider (and, eventually,
 * a real provider's league-key mapping) is built from.
 *
 * Player names generated by the mock provider are synthetic (not real athletes) —
 * this catalog exists to give the demo data a realistic shape, not to make factual
 * claims about real people's performance.
 */

export interface CatalogLeague {
  key: string;
  name: string;
  sportKey: string;
  sportName: string;
  externalKey: string; // The Odds API-style key, for when a real provider is wired in
  propTypes: string[];
  teams: string[]; // full team names
}

export const CATALOG: CatalogLeague[] = [
  {
    key: "nba",
    name: "NBA",
    sportKey: "basketball",
    sportName: "Basketball",
    externalKey: "basketball_nba",
    propTypes: ["points", "rebounds", "assists", "three_pointers_made"],
    teams: ["Lakers", "Celtics", "Warriors", "Bucks", "Nuggets", "Suns", "Knicks", "Heat"],
  },
  {
    key: "nfl",
    name: "NFL",
    sportKey: "football",
    sportName: "Football",
    externalKey: "americanfootball_nfl",
    propTypes: ["passing_yards", "rushing_yards", "receiving_yards", "receptions", "passing_touchdowns"],
    teams: ["Chiefs", "Bills", "Eagles", "Cowboys", "49ers", "Ravens", "Lions", "Dolphins"],
  },
  {
    key: "mlb",
    name: "MLB",
    sportKey: "baseball",
    sportName: "Baseball",
    externalKey: "baseball_mlb",
    propTypes: ["strikeouts", "hits", "total_bases", "home_runs"],
    teams: ["Yankees", "Dodgers", "Braves", "Astros", "Phillies", "Orioles", "Rangers", "Mets"],
  },
  {
    key: "epl",
    name: "Premier League",
    sportKey: "soccer",
    sportName: "Soccer",
    externalKey: "soccer_epl",
    propTypes: ["shots_on_target", "goals", "assists"],
    teams: ["Man City", "Arsenal", "Liverpool", "Man United", "Chelsea", "Tottenham", "Newcastle", "Aston Villa"],
  },
  {
    key: "bundesliga",
    name: "Bundesliga",
    sportKey: "soccer",
    sportName: "Soccer",
    externalKey: "soccer_germany_bundesliga",
    propTypes: ["shots_on_target", "goals", "assists"],
    teams: ["Bayern Munich", "Dortmund", "Leverkusen", "RB Leipzig", "Stuttgart", "Frankfurt"],
  },
  {
    key: "serie_a",
    name: "Serie A",
    sportKey: "soccer",
    sportName: "Soccer",
    externalKey: "soccer_italy_serie_a",
    propTypes: ["shots_on_target", "goals", "assists"],
    teams: ["Inter Milan", "AC Milan", "Juventus", "Napoli", "Roma", "Atalanta"],
  },
  {
    key: "ucl",
    name: "UEFA Champions League",
    sportKey: "soccer",
    sportName: "Soccer",
    externalKey: "soccer_uefa_champs_league",
    propTypes: ["shots_on_target", "goals", "assists"],
    teams: ["Real Madrid", "Man City", "Bayern Munich", "PSG", "Barcelona", "Inter Milan"],
  },
  {
    key: "uel",
    name: "UEFA Europa League",
    sportKey: "soccer",
    sportName: "Soccer",
    externalKey: "soccer_uefa_europa_league",
    propTypes: ["shots_on_target", "goals", "assists"],
    teams: ["Ajax", "Villarreal", "Rangers", "Lyon", "Sporting CP", "Real Sociedad"],
  },
  {
    key: "uecl",
    name: "UEFA Europa Conference League",
    sportKey: "soccer",
    sportName: "Soccer",
    externalKey: "soccer_uefa_europa_conference_league",
    propTypes: ["shots_on_target", "goals", "assists"],
    teams: ["Fiorentina", "West Ham", "Basel", "Nice", "Molde", "Slavia Prague"],
  },
  {
    key: "intl",
    name: "International",
    sportKey: "soccer",
    sportName: "Soccer",
    externalKey: "soccer_fifa_world_cup",
    propTypes: ["shots_on_target", "goals", "assists"],
    teams: ["USA", "Mexico", "Brazil", "Argentina", "England", "France"],
  },
];

export const FIRST_NAMES = [
  "Jalen", "Marcus", "Devon", "Andre", "Tyler", "Ethan", "Malik", "Cole", "Diego", "Lucas",
  "Mateo", "Kian", "Owen", "Rafael", "Theo", "Noah", "Elias", "Adrian", "Jamal", "Dominic",
];
export const LAST_NAMES = [
  "Carter", "Alvarez", "Whitfield", "Njoku", "Sullivan", "Bianchi", "Okafor", "Reyes", "Nilsson", "Park",
  "Mercer", "Delgado", "Hassan", "Kowalski", "Barrett", "Ferreira", "Lindqvist", "Osei", "Vance", "Brennan",
];
